services:
  asgard:
    build: .
    ports:
      - 4343:4343
      - 9229:9229
    volumes:
      - .:/asgard
      - /asgard/node_modules
      - /asgard/pnpm-store
    command: pnpm start:docker
    environment:
      - NODE_ENV=development
      - PORT=4343
      - HOST=