services:
  asgard_db:
    container_name: asgard_db
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - 5800:5432
    networks:
      - asgard_net
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  asgard:
    container_name: asgard
    build: .
    depends_on:
      asgard_db:
        condition: service_healthy
    ports:
      - 4343:4343
    volumes:
      - .:/asgard
      - /asgard/.pnpm-store
      - /asgard/node_modules
    command: ["pnpm", "start"]
    networks:
      - asgard_net
    environment:
      DB_URL: ${DATABASE_URL}
      DB_PORT: ${DB_PORT}
    stdin_open: true
    tty: true
    env_file:
      - .env

networks:
  asgard_net:
    driver: bridge
