services:
  asgard:
    container_name: asgard
    build: .
    ports:
      - 4343:4343
      - 9229:9229
    volumes:
      - .:/asgard
      - /asgard/.pnpm-store
      - /asgard/node_modules
    command: ["pnpm", "start"]
    networks:
      - asgard_net
    environment:
      DB_HOST: ep-hidden-rain-a2ahhswf.eu-central-1.aws.neon.tech
      DB_USER: asgard_db_owner
      DB_PASSWORD: e2SXkUBKQL0V
      DB_NAME: asgard_db
      DB_PORT: 5432
      PORT: 4343
      DATABASE_URL: postgresql://asgard_db_owner:e2SXkUBKQL0V@ep-hidden-rain-a2ahhswf.eu-central-1.aws.neon.tech/asgard_db?sslmode=require

networks:
  asgard_net:
    driver: bridge
