services:
  postgres:
    container_name: asgard_db
    image: postgres:15-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    networks:
      - asgard_net
    environment:
      POSTGRES_DB: asgard_db
      POSTGRES_HOST_AUTH_METHOD: trust
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    networks:
      - asgard_net
    restart: always
    environment:
      
      PGADMIN_DEFAULT_EMAIL: davidshemang@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456de

  asgard:
    container_name: asgard
    build: .
    depends_on:
      - postgres
    ports:
      - 4343:4343
      - 9229:9229  # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker
    networks:
      - asgard_net
    environment:
      DATABASE_URL: postgres://postgres@postgres/asgard_db
      PORT: 4343

networks:
  asgard_net:
    driver: bridge