services:
  app:
    container_name: server
    image: asgard-app:latest
    # restart: always
    build: .
    ports:
      - "4343:4343"
    links:
      - "database"
    env_file:
      - ${ENV_FILE:-.noenv}
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=0.0.0.0
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      - asgard-net
    volumes:
      - ./package.json:/asgard/package.json
      - ./tsconfig.json:/asgard/tsconfig.json
      # - ./start:/asgard/start
      # - ./config:/asgard/config
      # - ./app:/asgard/app
      - /asgard/node_modules
    command: >
      sh -c "
      if [ \"$RUN_MIGRATIONS\" = \"true\" ]; then
          echo 'Running migrations...';
          node ace migration:run --force;
      else
          echo 'Skipping migrations.';
      fi &&
      pnpm start
      " 

  database:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - 5800:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - asgard-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    container_name: redis
    image: redis:7-alpine
    ports:
      - 6385:6379
    volumes:
      - cache-data:/data
    networks:
      - asgard-net

networks:
  asgard-net:
    driver: bridge

volumes:
  db-data:
  cache-data:
