name: Continous Deployment

on:
    push:
        branches:
        - main
 
jobs:   
        build:
            runs-on: [ubuntu-latest]
            steps:
              - name: Checkout source
                uses: actions/checkout@v3
              - name: Login to Docker Hub
                run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
              - name: Build docker image
                run: docker build -t asgard .
              - name: Push docker image to docker hub
                run: docker push asgard:latest
        
        deploy:
            needs: build
            runs-on: [aws-ec2]
            steps:
              - name: Pull image from docker hub
                run: docker pull asgard:latest
              - name:  Delete old Container
                run: docker rm -f asgard-container || true
              - name: Run new container
                run: docker run -d -p 4343:4343 --name asgard-container asgard