name: Pull Request Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Run Tests
        run: |
            yarn --frozen-lockfile
            yarn build
            yarn lint
            yarn test:run

      - name: Build Image
        run: docker build -t asgard .
