name: Pull Request Workflow

on:
  pull_request:
    branches:
      - develop
      - main

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set test Environment Variables
        run: echo "Setting environment variables"
        env:
          APP_KEY: "test_app_key"
          HOST: "localhost"
          LOG_LEVEL: "info"
          DB_HOST: "localhost"
          DB_PORT: "5432"
          DB_USER: "test_user"
          DB_DATABASE: "test_db"
          REDIS_HOST: "localhost"
          REDIS_PORT: "6379"
          FACEBOOK_CLIENT_ID: "test_facebook_client_id"
          FACEBOOK_CLIENT_SECRET: "test_facebook_client_secret"
          GOOGLE_CLIENT_ID: "test_google_client_id"
          GOOGLE_CLIENT_SECRET: "test_google_client_secret"

      - name: Run Tests
        run: |
            pnpm i --frozen-lockfile
            pnpm build
            pnpm lint
            pnpm test
      
      - name: Build Image
        run: docker build -t server .
