name: Pull Request Workflow

on:
  pull_request:
    branches:
      - develop
      - main

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Run Tests
        run: |
            pnpm i --frozen-lockfile
            pnpm build
            pnpm lint
            pnpm test
      
      - name: Build Image
        run: docker build -t server .
